clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  vue-build:
    image: node:lts-alpine
    commands:
      - apk add git bash
      - find js/ -type f -delete
      - npm install
      - npm run build
      - git status
      - bash -c "[[ ! \"`git status --porcelain js/`\" ]] || ( echo 'Uncommited changes in vue build' && exit 1 )"
    when:
      matrix:
        TESTS: vue-build

matrix:
  include:
    - TESTS: vue-build
